name: ${project.name}
main: net.hyze.factions.framework.FactionsPlugin
version: ${git.commit.id.describe-short}
depend: [Core-Spigot, ProtocolLib, Homes, Containers, Economy, SignShop, Market, Kits, Beacon]